"""Compatibility imports for shared experiment utilities.

Implementation lives in dlm_steering; this module preserves existing imports.
"""
from dlm_steering.paths import (
    DATA_DIR,
)
from dlm_steering.runtime.constants import (
    MODEL,
    MODEL_KEY,
    add_model_arg,
    MODEL_NAME,
    MASK_ID,
    MASK_TOKEN,
    EOT_ID,
    USER_HEADER_ID,
    NEWLINE_ID,
    TURN_BREAKERS,
    N_LAYERS,
    OUT_DIR,
    DETECTOR_LAYER,
    STEER_LAYERS,
    MODEL_LOCK,
    block_index,
    FIT_LAYERS,
    ERROR_SENTINEL,
)
from dlm_steering.runtime.data import (
    JBB_HARMFUL_GLOB,
    JBB_BENIGN_GLOB,
    XSTEST_GLOB,
    WJ_EVAL_GLOB,
    TRUTHFULQA_GLOB,
    GSM8K_GLOB,
    MMLU_GLOB,
    WALLEDAI_GLOB,
    LEGACY_HF_ROOT,
    _hf_roots,
    hf_glob,
    HARMFUL_SOURCES,
    BENIGN_SOURCES,
    UTILITY_SOURCES,
    PROMPT_SOURCES,
    LETTERS,
    MC_INSTRUCTION,
    GSM8K_INSTRUCTION,
    MATH_INSTRUCTION,
    _read_arrow,
    format_mc,
    load_utility_prompts,
    load_prompts,
    load_eval_prompts,
)
from dlm_steering.runtime.models import (
    ShiftedLogits,
    model_blocks,
    load_model,
    load_llada,
    seed_all,
    enable_reproducibility,
    release_cublas_env,
    force_math_attention,
    prompt_token_ids,
    encode_prompt,
    load_detector_bundle,
    load_detector,
    steer_vector_at,
)
from dlm_steering.runtime.utils import (
    write_json,
    step_scale,
    auroc,
)
from dlm_steering.runtime.execution import (
    strip_argv_flag,
    shard_slices,
    parse_gpu_ids,
    WORKER_MIB,
    _free_mib,
    worker_devices,
    plan_shards,
    child_launcher,
    spawn_shards,
    wait_merge_shards,
    run_eval_shards,
    _persistent_model,
    _run_persistent_job,
    read_jobs,
    run_persistent_jobs,
)
